import { Partner, Task, LogbookEntry, Milestone, Recipe } from '@/types';

// Socios configurables (puedes cambiar sus nombres reales en la app)
export const DEFAULT_PARTNERS: Partner[] = [
  {
    id: 'partner-1',
    name: 'Socio 1',
    shortName: 'Socio 1',
    email: 'socio1@migaliabakery.com',
    role: 'Cofundador',
    avatar: '1',
  },
  {
    id: 'partner-2',
    name: 'Socio 2',
    shortName: 'Socio 2',
    email: 'socio2@migaliabakery.com',
    role: 'Cofundador',
    avatar: '2',
  },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 'task-1',
    title: 'Protocolización de Acta Constitutiva S.A. de C.V.',
    description: 'Redacción con Notario Público incorporando cláusulas corporativas aptas para inversión extranjera y traspaso de utilidades a EE. UU. (Visa E-2).',
    category: 'Legal & Permisos',
    assignedTo: 'partner-1',
    priority: 'urgent',
    status: 'todo',
    startDate: '2026-09-15',
    dueDate: '2026-09-29',
    estimatedCost: 16500,
    actualCost: 0,
    isBlocked: false,
    createdAt: '2026-09-14',
    subtasks: [
      { id: 'st-1-1', title: 'Solicitar autorización de denominación ante Secretaría de Economía (MIGALIA S.A. de C.V.)', completed: false },
      { id: 'st-1-2', title: 'Definir porcentaje accionario 50/50 entre socios', completed: false },
      { id: 'st-1-3', title: 'Firma presencial en Notaría Pública', completed: false },
      { id: 'st-1-4', title: 'Inscripción en el Registro Público de la Propiedad y del Comercio', completed: false },
    ],
  },
  {
    id: 'task-2',
    title: 'Registro de Marca Mixta MIGALIA (Clases 30 y 43)',
    description: 'Ingreso de solicitud oficial del logo y nombre ante el Instituto Mexicano de la Propiedad Industrial en Clase 30 (panadería y repostería) y Clase 43 (servicios de cafetería/alimentos para llevar).',
    category: 'Legal & Permisos',
    assignedTo: 'partner-1',
    priority: 'high',
    status: 'todo',
    startDate: '2026-09-16',
    dueDate: '2026-09-23',
    estimatedCost: 5500,
    actualCost: 0,
    isBlocked: false,
    createdAt: '2026-09-14',
    subtasks: [
      { id: 'st-2-1', title: 'Búsqueda fonética final en Marcanet', completed: false },
      { id: 'st-2-2', title: 'Pago de derechos ante el SAT/IMPI (2 clases)', completed: false },
      { id: 'st-2-3', title: 'Llenado y firma electrónica de expediente con logo vectorial', completed: false },
      { id: 'st-2-4', title: 'Guardar número de expediente para seguimiento', completed: false },
    ],
  },
  {
    id: 'task-3',
    title: 'Trámite de e.firma y Cuenta de Cheques PyME',
    description: 'Separación estricta de finanzas. Todo peso gastado del CAPEX debe pasar por esta cuenta para comprobación fiscal limpia ante USCIS (Visa E-2).',
    category: 'Finanzas',
    assignedTo: 'partner-2',
    priority: 'urgent',
    status: 'todo',
    startDate: '2026-09-30',
    dueDate: '2026-10-09',
    estimatedCost: 0,
    actualCost: 0,
    isBlocked: true,
    blockerReason: 'Depende de tener el Acta Constitutiva lista',
    createdAt: '2026-09-14',
    subtasks: [
      { id: 'st-3-1', title: 'Cita y obtención del RFC corporativo y e.firma en el SAT', completed: false },
      { id: 'st-3-2', title: 'Comparativa de comisiones en bancos (BBVA / Santander / Banregio)', completed: false },
      { id: 'st-3-3', title: 'Firma mancomunada y depósito del capital social inicial', completed: false },
    ],
  },
  {
    id: 'task-4',
    title: 'Pruebas y Costeo del Menú Insignia (Cookie Fries y Galletas NY)',
    description: 'Sesiones de prueba para calibrar tiempos de horneado, texturas y costeo por gramo en el software para asegurar margen bruto > 75%.',
    category: 'Recetas & Menú',
    assignedTo: 'partner-2',
    priority: 'high',
    status: 'todo',
    startDate: '2026-09-18',
    dueDate: '2026-10-02',
    estimatedCost: 4000,
    actualCost: 0,
    isBlocked: false,
    createdAt: '2026-09-14',
    subtasks: [
      { id: 'st-4-1', title: 'Estandarización de receta de Cookie Fries y formulación de dips', completed: false },
      { id: 'st-4-2', title: 'Calibración de masa para galletas rellenas estilo New York', completed: false },
      { id: 'st-4-3', title: 'Documentar ficha técnica de gramaje y rendimiento por lote en hoja maestra', completed: false },
      { id: 'st-4-4', title: 'Fijar precio de venta al público sugerido', completed: false },
    ],
  },
  {
    id: 'task-5',
    title: 'Pedido Inicial de Cajas Giftable y Vasos de Café',
    description: 'Producción de cajas rígidas color crema con logotipo espresso, conos estilo papas fritas con tintero para dip y vasos térmicos para café.',
    category: 'Branding',
    assignedTo: 'partner-1',
    priority: 'medium',
    status: 'todo',
    startDate: '2026-09-22',
    dueDate: '2026-10-10',
    estimatedCost: 12000,
    actualCost: 0,
    isBlocked: false,
    createdAt: '2026-09-14',
    subtasks: [
      { id: 'st-5-1', title: 'Aprobación de pruebas de color de imprenta (Espresso #382820 sobre cartulina marfil)', completed: false },
      { id: 'st-5-2', title: 'Mandar a producir 1,000 cajas tipo joyería', completed: false },
      { id: 'st-5-3', title: 'Mandar a producir 1,000 cajas/conos para Cookie Fries', completed: false },
      { id: 'st-5-4', title: 'Compra de stock inicial de vasos biodegradables de 8 oz y 12 oz con fajillas', completed: false },
    ],
  },
  {
    id: 'task-6',
    title: 'Ejecución de Venta Piloto (Pop-Up Weekend en Cholula/Sonata)',
    description: 'Validación cara a cara de 150 piezas de repostería creativa para medir velocidad de venta y aceptación del precio objetivo ($65-$75 MXN).',
    category: 'Comercial & Ventas',
    assignedTo: 'partner-2',
    priority: 'high',
    status: 'todo',
    startDate: '2026-10-03',
    dueDate: '2026-10-18',
    estimatedCost: 3000,
    actualCost: 0,
    isBlocked: false,
    createdAt: '2026-09-14',
    subtasks: [
      { id: 'st-6-1', title: 'Renta de stand en bazar de diseño (San Andrés Cholula / Lomas de Angelópolis)', completed: false },
      { id: 'st-6-2', title: 'Montaje de mesa con mantel de lino, display de cristal y banners sobrios', completed: false },
      { id: 'st-6-3', title: 'Cobro con terminal Clip/MercadoPago y registro de transacciones', completed: false },
      { id: 'st-6-4', title: 'Encuesta corta a clientes sobre sabor y precio percibido', completed: false },
    ],
  },
  {
    id: 'task-7',
    title: 'Negociación y Contrato de Local Boutique (25–35 m²)',
    description: 'Cierre de local comercial compacto a pie de calle o en plaza abierta. Verificar uso de suelo comercial y carga eléctrica para maquinaria de horneado.',
    category: 'Obra & Interiorismo',
    assignedTo: 'partner-1',
    priority: 'urgent',
    status: 'todo',
    startDate: '2026-09-25',
    dueDate: '2026-10-15',
    estimatedCost: 24000,
    actualCost: 0,
    isBlocked: false,
    createdAt: '2026-09-14',
    subtasks: [
      { id: 'st-7-1', title: 'Revisión de contrato con abogado (período de gracia para remodelación de 30 días)', completed: false },
      { id: 'st-7-2', title: 'Verificación de factibilidad de agua y conexión eléctrica bifásica/trifásica', completed: false },
      { id: 'st-7-3', title: 'Firma de contrato y pago de depósito en garantía + primer mes de renta', completed: false },
    ],
  },
  {
    id: 'task-8',
    title: 'Remodelación y Acabados Estilo Japandi / Warm Minimalist',
    description: 'Aplicación de acabado caliza/chukum en muros, herrería minimalista, barra perimetral de roble y luminarias cálidas (2700K).',
    category: 'Obra & Interiorismo',
    assignedTo: 'partner-1',
    priority: 'high',
    status: 'todo',
    startDate: '2026-10-16',
    dueDate: '2026-11-10',
    estimatedCost: 45000,
    actualCost: 0,
    isBlocked: true,
    blockerReason: 'Depende de la entrega del local firmado',
    createdAt: '2026-09-14',
    subtasks: [
      { id: 'st-8-1', title: 'Instalaciones eléctricas dedicadas para horno y máquina de café', completed: false },
      { id: 'st-8-2', title: 'Aplicación de recubrimiento texturizado en muros', completed: false },
      { id: 'st-8-3', title: 'Fabricación y montaje de barra de servicio en madera clara', completed: false },
      { id: 'st-8-4', title: 'Montaje de letrero exterior con iluminación indirecta', completed: false },
    ],
  },
  {
    id: 'task-9',
    title: 'Compra e Instalación de Horno de Convección y Batidora',
    description: 'Adquisición de horno de convección digital de 4 charolas (Unox o similar), batidora planetaria de 20 litros y mesa de trabajo de acero inoxidable grado alimenticio.',
    category: 'Equipamiento',
    assignedTo: 'partner-2',
    priority: 'urgent',
    status: 'todo',
    startDate: '2026-10-10',
    dueDate: '2026-10-30',
    estimatedCost: 85000,
    actualCost: 0,
    isBlocked: false,
    createdAt: '2026-09-14',
    subtasks: [
      { id: 'st-9-1', title: 'Comparativa de cotizaciones con proveedores de Puebla/CDMX', completed: false },
      { id: 'st-9-2', title: 'Pago de anticipo del 50% y programación de entrega', completed: false },
      { id: 'st-9-3', title: 'Pruebas de encendido, calibración de temperatura y extracción de calor', completed: false },
    ],
  },
  {
    id: 'task-10',
    title: 'Compra y Calibración de Máquina de Espresso y Molino',
    description: 'Máquina comercial de 1 grupo con molino micrométrico de muelas. Cierre con tostador de café de especialidad de la Sierra Norte de Puebla.',
    category: 'Equipamiento',
    assignedTo: 'partner-2',
    priority: 'medium',
    status: 'todo',
    startDate: '2026-10-15',
    dueDate: '2026-11-05',
    estimatedCost: 35000,
    actualCost: 0,
    isBlocked: false,
    createdAt: '2026-09-14',
    subtasks: [
      { id: 'st-10-1', title: 'Adquisición de máquina comercial de espresso y molino on-demand', completed: false },
      { id: 'st-10-2', title: 'Instalación de filtro purificador de agua por ósmosis inversa', completed: false },
      { id: 'st-10-3', title: 'Calibración del espresso (ratio, molienda y tiempo de extracción)', completed: false },
    ],
  },
  {
    id: 'task-11',
    title: 'Montaje de Vitrina de Cristal y Sistema POS',
    description: 'Vitrina de cristal templado sin marcos para exhibir las piezas estrella y tablet con software de cobro en la nube con lector de tarjetas.',
    category: 'Equipamiento',
    assignedTo: 'partner-1',
    priority: 'medium',
    status: 'todo',
    startDate: '2026-11-01',
    dueDate: '2026-11-12',
    estimatedCost: 16000,
    actualCost: 0,
    isBlocked: false,
    createdAt: '2026-09-14',
    subtasks: [
      { id: 'st-11-1', title: 'Instalación de vitrina de cristal sobre barra', completed: false },
      { id: 'st-11-2', title: 'Configuración de catálogo y precios en el sistema de cobro', completed: false },
      { id: 'st-11-3', title: 'Configuración de impresora térmica de tickets', completed: false },
    ],
  },
  {
    id: 'task-12',
    title: 'Licencia de Funcionamiento y Aviso COFEPRIS',
    description: 'Cumplimiento normativo para elaboración de alimentos para llevar en el municipio de San Andrés Cholula / Puebla.',
    category: 'Legal & Permisos',
    assignedTo: 'partner-1',
    priority: 'high',
    status: 'todo',
    startDate: '2026-10-20',
    dueDate: '2026-11-15',
    estimatedCost: 6500,
    actualCost: 0,
    isBlocked: true,
    blockerReason: 'Requiere contrato de arrendamiento y predial del local',
    createdAt: '2026-09-14',
    subtasks: [
      { id: 'st-12-1', title: 'Dictamen de Protección Civil (extintor, botiquín y señalética)', completed: false },
      { id: 'st-12-2', title: 'Presentar Aviso de Funcionamiento Sanitario (NOM-251)', completed: false },
      { id: 'st-12-3', title: 'Ingreso de expediente para Licencia de Funcionamiento Comercial', completed: false },
    ],
  },
  {
    id: 'task-13',
    title: 'Adquisición de Primer Inventario de Producción',
    description: 'Harina de alta fuerza, mantequilla europea/artesanal con 82% grasa, chocolate de cobertura semiamargo, fruta para coulis y café en grano.',
    category: 'Proveedores',
    assignedTo: 'partner-2',
    priority: 'high',
    status: 'todo',
    startDate: '2026-11-08',
    dueDate: '2026-11-16',
    estimatedCost: 12000,
    actualCost: 0,
    isBlocked: false,
    createdAt: '2026-09-14',
    subtasks: [
      { id: 'st-13-1', title: 'Compra de insumos secos (harina, azúcares, sal marina)', completed: false },
      { id: 'st-13-2', title: 'Compra de lácteos y mantequilla', completed: false },
      { id: 'st-13-3', title: 'Compra de café de especialidad fresco', completed: false },
    ],
  },
  {
    id: 'task-14',
    title: 'Entrenamiento de Personal (Barista y Horno)',
    description: 'Capacitación de los 2 colaboradores de turno para asegurar horneado exacto, despacho ágil y servicio estandarizado.',
    category: 'Operaciones',
    assignedTo: 'partner-2',
    priority: 'medium',
    status: 'todo',
    startDate: '2026-11-12',
    dueDate: '2026-11-19',
    estimatedCost: 4000,
    actualCost: 0,
    isBlocked: false,
    createdAt: '2026-09-14',
    subtasks: [
      { id: 'st-14-1', title: 'Simulación de apertura matutina (encendido de hornos y vitrina)', completed: false },
      { id: 'st-14-2', title: 'Tiempos de servicio por cliente (objetivo < 90 segundos por orden)', completed: false },
      { id: 'st-14-3', title: 'Checklist de limpieza y sanitización de cierre', completed: false },
    ],
  },
  {
    id: 'task-15',
    title: 'Apertura y Campaña de Lanzamiento en Redes',
    description: 'Jornada de apertura a puertas cerradas con micro-influencers gastronómicos locales de Puebla, seguida de la apertura oficial al público general.',
    category: 'Comercial & Ventas',
    assignedTo: 'partner-1',
    priority: 'urgent',
    status: 'todo',
    startDate: '2026-11-20',
    dueDate: '2026-11-25',
    estimatedCost: 6000,
    actualCost: 0,
    isBlocked: true,
    blockerReason: 'Depende de la inspección de Protección Civil y luz verde de obra',
    createdAt: '2026-09-14',
    subtasks: [
      { id: 'st-15-1', title: 'Envío de cajas de degustación a creadores de contenido gastronómico', completed: false },
      { id: 'st-15-2', title: 'Producción del video de inauguración para TikTok e Instagram', completed: false },
      { id: 'st-15-3', title: 'Apertura al público y primer corte de caja', completed: false },
    ],
  },
];

export const EMPTY_TASKS: Task[] = [];
export const EMPTY_LOGBOOK: LogbookEntry[] = [];

// Hitos de referencia en timeline (editables y eliminables)
export const INITIAL_MILESTONES: Milestone[] = [
  {
    id: 'ms-1',
    title: 'Constitución Legal & Trámites Notariales',
    phase: 'Fase I: Legal',
    deadline: '2026-10-15',
    status: 'in_progress',
    progress: 25,
  },
  {
    id: 'ms-2',
    title: 'Arrendamiento & Obra Chukum Local',
    phase: 'Fase I: Obra',
    deadline: '2026-11-30',
    status: 'pending',
    progress: 0,
  },
  {
    id: 'ms-3',
    title: 'Equipamiento & Pruebas de Horno',
    phase: 'Fase I: Producción',
    deadline: '2026-12-20',
    status: 'pending',
    progress: 0,
  },
  {
    id: 'ms-4',
    title: 'Apertura Oficial Boutique Grab & Go Puebla',
    phase: 'Fase I: Lanzamiento',
    deadline: '2027-01-15',
    status: 'pending',
    progress: 0,
  },
];

export const INITIAL_RECIPES: Recipe[] = [
  {
    id: 'rec-1',
    title: 'COOKIE FRIES CON DIP DE FRUTOS ROJOS (INSIGNIA)',
    yieldCount: '10 PERSONAS / 20 CONOS',
    presentation: 'CONO KRAFT TIPO PAPAS CON TINTERO PARA DIP',
    standardizedFor: 'Recetario estandarizado y costeado',
    category: 'Repostería Insignia',
    ingredients: [
      { id: 'ing-1', name: 'MANTEQUILLA ARTESANAL 82% GRASA', quantity: 0.350, unit: 'KG', unitCost: 160, totalCost: 56 },
      { id: 'ing-2', name: 'AZÚCAR MASCABADO OSCURO', quantity: 0.250, unit: 'KG', unitCost: 48, totalCost: 12 },
      { id: 'ing-3', name: 'AZÚCAR REFINADA', quantity: 0.150, unit: 'KG', unitCost: 38, totalCost: 5.7 },
      { id: 'ing-4', name: 'HUEVO FRESCO DE GRANJA', quantity: 0.120, unit: 'KG', unitCost: 45, totalCost: 5.4 },
      { id: 'ing-5', name: 'EXTRACTO NATURAL DE VAINILLA', quantity: 0.015, unit: 'LT', unitCost: 350, totalCost: 5.25 },
      { id: 'ing-6', name: 'HARINA DE TRIGO TODO USO', quantity: 0.550, unit: 'KG', unitCost: 22, totalCost: 12.1 },
      { id: 'ing-7', name: 'FÉCULA DE MAÍZ', quantity: 0.040, unit: 'KG', unitCost: 40, totalCost: 1.6 },
      { id: 'ing-8', name: 'BICARBONATO DE SODIO', quantity: 0.008, unit: 'KG', unitCost: 35, totalCost: 0.28 },
      { id: 'ing-9', name: 'SAL MARINA DE COLIMA', quantity: 0.006, unit: 'KG', unitCost: 30, totalCost: 0.18 },
      { id: 'ing-10', name: 'CHOCOLATE CHIPS 60% CACAO', quantity: 0.300, unit: 'KG', unitCost: 240, totalCost: 72 },
      { id: 'ing-sub-1', name: 'SUB-RECETA DIP DE FRUTOS ROJOS Y MARACUYÁ', quantity: 0, unit: 'C/S', unitCost: 0, totalCost: 0, isSubrecipeTitle: true },
      { id: 'ing-11', name: 'FRAMBUESAS Y MORAS FRESCAS', quantity: 0.250, unit: 'KG', unitCost: 120, totalCost: 30 },
      { id: 'ing-12', name: 'PULPA DE MARACUYÁ NATURAL', quantity: 0.100, unit: 'KG', unitCost: 90, totalCost: 9 },
      { id: 'ing-13', name: 'AZÚCAR REFINADA PARA ALMÍBAR', quantity: 0.080, unit: 'KG', unitCost: 38, totalCost: 3.04 },
    ],
    miseEnPlace: [
      'Pesar y atemperar la mantequilla a punto pomada (20°C).',
      'Tamizar juntos la harina, fécula de maíz, bicarbonato y sal marina.',
      'Lavar, desinfectar y escurrir los frutos rojos.',
      'Tener listos los cortadores ondulados tipo crinkle-cut para las galletas.',
    ],
    preparation: [
      'Acremar la mantequilla pomada con ambos azúcares en batidora planetaria con pala durante 4 minutos a velocidad media hasta emulsionar.',
      'Incorporar los huevos uno a uno y la vainilla natural; batir solo hasta integrar.',
      'Añadir los secos tamizados en dos partes a velocidad baja. Integrar las chispas de chocolate de manera envolvente.',
      'Extender la masa entre papel encerado a 1.2 cm de grosor y congelar durante 35 minutos.',
      'Cortar en tiras uniformes simulando papas a la francesa (Cookie Fries).',
      'Hornear en horno de convección a 170°C durante 11 a 13 minutos hasta obtener bordes dorados crujientes y centro suave.',
      'Para el dip: cocer frutos rojos con pulpa de maracuyá y azúcar a fuego medio durante 8 minutos hasta reducir a textura salsa.',
      'Montar en cono de cartulina kraft marfil con el tintero de dip al lado.',
    ],
    notes: 'Receta insignia de Migalia. Margen de ganancia estimado: 78%.',
    createdAt: '2026-09-15',
  },
];

export const INITIAL_DOCUMENTS: import('@/types').MigaliaDocument[] = [
  {
    id: 'doc-1',
    title: 'Acuerdo de Voluntades & Cláusulas Corporativas E-2',
    type: 'doc',
    folder: 'Legal & Constitución',
    content: `<h2>ACUERDO PRE-CONSTITUTIVO ENTRE COFUNDADORES</h2><p><strong>PROYECTO:</strong> MIGALIA S.A. DE C.V.</p><p><strong>OBJETIVO:</strong> Establecer las bases operativas, distribución accionaria 50/50 y mecanismos de repatriación de dividendos compatibles con el trámite de inversión para <strong>Visa E-2</strong> en Estados Unidos.</p><h3>1. Distribución Accionaria y Gobierno Corporativo</h3><ul><li><strong>Mario Alberto González Cervantes:</strong> 50% de las acciones Serie A. Enfoque: Finanzas, Expansión, Dirección Comercial y Legal.</li><li><strong>Susy:</strong> 50% de las acciones Serie A. Enfoque: Dirección Culinaria, Operación de Boutique y Calidad.</li></ul><h3>2. Políticas de Reinversión de Utilidades</h3><p>Durante los primeros 12 meses de operación, el 70% del flujo neto será reinvertido en la apertura del segundo punto de venta en Puebla (Angelópolis / Sonata), reservando el 30% restante para reparto de dividendos.</p>`,
    authorName: 'Mario',
    createdAt: '2026-09-15',
    updatedAt: '2026-09-15',
    isPinned: true,
  },
  {
    id: 'doc-2',
    title: 'Presupuesto y Proyección de Inversión Inicial (CAPEX)',
    type: 'sheet',
    folder: 'Finanzas & Inversión',
    content: JSON.stringify({
      columns: ['Concepto', 'Categoría', 'Presupuesto Estimado', 'Gasto Real Pagado', 'Diferencia / Estatus'],
      rows: [
        ['Horno de Convección Eléctrico 4 Charolas', 'Equipamiento', '42000', '0', 'Cotizado'],
        ['Batidora Planetaria 20 Litros', 'Equipamiento', '28500', '0', 'Por autorizar'],
        ['Refrigerador / Vitrina Panorámica Cristal Curvo', 'Equipamiento', '35000', '0', 'Búsqueda'],
        ['Protocolización Acta Constitutiva S.A. de C.V.', 'Legal', '16500', '0', 'En Notaría'],
        ['Registro de Marca Mixta ante el IMPI', 'Legal', '3500', '0', 'Por ingresar'],
        ['Adecuación Arquitectónica e Instalaciones', 'Obra & Local', '45000', '0', 'Estimado'],
        ['Empaque Inicial (1,000 conos + 1,000 cajas)', 'Branding', '15000', '0', 'Cotizado con imprenta'],
        ['Materia Prima Inicial (Harinas, Mantequillas, Chocolate)', 'Inventario', '18000', '0', 'Por pedir'],
      ]
    }),
    authorName: 'Mario',
    createdAt: '2026-09-15',
    updatedAt: '2026-09-15',
    isPinned: true,
  },
  {
    id: 'doc-3',
    title: 'Manual de Procedimientos de Apertura y Cierre de Boutique',
    type: 'doc',
    folder: 'Operaciones & Taller',
    content: `<h2>CHECKLIST DIARIO DE APERTURA Y CONTROL DE CALIDAD</h2><p><strong>HORARIO DE APERTURA AL PÚBLICO:</strong> 08:30 AM</p><h3>Apertura (07:30 AM - 08:30 AM)</h3><ul><li>[ ] Encendido de horno de convección a temperatura base (170°C).</li><li>[ ] Primer lote de Cookie Fries y horneado fresco del día.</li><li>[ ] Montaje y acomodo en vitrina con iluminación cálida.</li><li>[ ] Verificación de temperatura de salsas y dips (refrigeración &lt; 4°C).</li><li>[ ] Apertura de caja registradora y fondo inicial de cambio ($1,500 MXN).</li></ul><h3>Cierre (08:30 PM - 09:15 PM)</h3><ul><li>[ ] Corte de caja diario y conciliación con sistema TPV.</li><li>[ ] Registro de mermas del día.</li><li>[ ] Limpieza profunda de superficies y desconexión de equipos secundarios.</li></ul>`,
    authorName: 'Susy',
    createdAt: '2026-09-15',
    updatedAt: '2026-09-15',
  }
];
