import { Partner, Task, LogbookEntry, Milestone } from '@/types';

export const INITIAL_PARTNERS: Partner[] = [
  {
    id: 'partner-1',
    name: 'Socio Fundador 1',
    shortName: 'Socio A',
    email: 'socio1@migalia.mx',
    role: 'Operaciones & Producción',
    avatar: 'A',
  },
  {
    id: 'partner-2',
    name: 'Socio Fundador 2',
    shortName: 'Socio B',
    email: 'socio2@migalia.mx',
    role: 'Administración & Expansión',
    avatar: 'B',
  },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 'task-1',
    title: 'Cotizar y comparar acabados de chukum y madera de roble claro',
    description: 'Solicitar presupuesto a 3 aplicadores de chukum en Puebla para muros interiores y cotizar carpintería de barra compacta.',
    status: 'in_progress',
    priority: 'high',
    assignedTo: 'partner-1',
    category: 'Obra & Interiorismo',
    dueDate: '2026-09-25',
    subtasks: [
      { id: 'st-1', title: 'Medir espacio exacto (25-35 m²)', completed: true },
      { id: 'st-2', title: 'Pedir muestras de textura caliza 2700K', completed: true },
      { id: 'st-3', title: 'Definir carpintero para la barra de roble', completed: false },
    ],
    createdAt: '2026-09-10',
  },
  {
    id: 'task-2',
    title: 'Constitución legal S.A. de C.V. y registro IMPI',
    description: 'Reunión con notario para firma de acta constitutiva y alta de registro de marca en clases 30 y 43 ante el IMPI.',
    status: 'in_progress',
    priority: 'urgent',
    assignedTo: 'partner-2',
    category: 'Legal & S.A.',
    dueDate: '2026-09-20',
    subtasks: [
      { id: 'st-4', title: 'Revisión de estatutos con abogado', completed: true },
      { id: 'st-5', title: 'Solicitud de uso de denominación en Economía', completed: true },
      { id: 'st-6', title: 'Firma notarial y depósito de capital semilla ($250k MXN)', completed: false },
    ],
    createdAt: '2026-09-08',
  },
  {
    id: 'task-3',
    title: 'Pruebas de horneado: Cookie Fries (Papas de Galleta) y Dip',
    description: 'Estandarizar gramajes y tiempos para la galleta trampantojo shortbread y el dip de frambuesa artesanal.',
    status: 'todo',
    priority: 'high',
    assignedTo: 'partner-1',
    category: 'Recetas & Pruebas',
    dueDate: '2026-09-28',
    subtasks: [
      { id: 'st-7', title: 'Comprar mantequilla Gloria / importada de alta fermentación', completed: true },
      { id: 'st-8', title: 'Calibrar temperatura de horneado para crujiente óptimo', completed: false },
      { id: 'st-9', title: 'Diseño de porción para la caja tipo papas fritas', completed: false },
    ],
    createdAt: '2026-09-12',
  },
  {
    id: 'task-4',
    title: 'Diseño y cotización de empaque "Giftable" tipo joyería',
    description: 'Desarrollar prototipo de caja rígida con interiores a la medida para detonar compras corporativas y regalos.',
    status: 'todo',
    priority: 'medium',
    assignedTo: 'partner-2',
    category: 'Empaque & Marca',
    dueDate: '2026-10-05',
    subtasks: [
      { id: 'st-10', title: 'Definir dimensiones para cajas de 4 y 8 piezas', completed: false },
      { id: 'st-11', title: 'Cotizar con imprenta local acabado mate y hot stamping dorado', completed: false },
    ],
    createdAt: '2026-09-14',
  },
  {
    id: 'task-5',
    title: 'Selección de máquina espresso 1 grupo y molino micrométrico',
    description: 'Comparar opciones de máquina comercial italiana (La Marzocco / Sanremo / Nuova Simonelli) para barra compacta.',
    status: 'backlog',
    priority: 'medium',
    assignedTo: 'partner-1',
    category: 'Equipamiento',
    dueDate: '2026-10-15',
    subtasks: [],
    createdAt: '2026-09-14',
  },
  {
    id: 'task-6',
    title: 'Estructurar carpeta fiscal y contable inicial para trazabilidad E-2',
    description: 'Asegurar que cada peso invertido en equipamiento y obra tenga CFDI legal a nombre de la persona moral para el futuro expediente consular.',
    status: 'review',
    priority: 'high',
    assignedTo: 'partner-2',
    category: 'Estrategia E-2',
    dueDate: '2026-09-30',
    subtasks: [
      { id: 'st-12', title: 'Apertura de cuenta bancaria empresarial', completed: false },
      { id: 'st-13', title: 'Plantilla de control de CAPEX vs Presupuesto ($250k MXN)', completed: true },
    ],
    createdAt: '2026-09-11',
  },
];

export const INITIAL_LOGBOOK: LogbookEntry[] = [
  {
    id: 'log-1',
    title: 'Acuerdo de Distribución de Inversión Semilla ($250,000 MXN)',
    content: 'Se formaliza que el capital se destinará principalmente a Equipamiento de horneado ($85k), Obra/Interiorismo ($45k) y Capital de trabajo de reserva ($35k). Ambos socios acuerdan mantener disciplina estricta de costos.',
    category: 'Decisión de Negocio',
    authorId: 'partner-2',
    authorName: 'Socio B',
    date: '2026-09-10',
  },
  {
    id: 'log-2',
    title: 'Definición de Concepto Arquitectónico Japandi / Warm Minimalist',
    content: 'Reunión presencial para definir que el local no tendrá colores estridentes. La atmósfera será de lujo accesible: muros caliza texturizados, luz 2700K y barra de madera clara. Se elimina la vajilla tradicional para operar formato Grab & Go con 2 personas.',
    category: 'Reunión & Acuerdos',
    authorId: 'partner-1',
    authorName: 'Socio A',
    date: '2026-09-05',
  },
  {
    id: 'log-3',
    title: 'Validación del producto estrella Trampantojo: Cookie Fries',
    content: 'La prueba inicial de galleta estilo papas fritas con dip de fruta demostró un potencial de viralidad orgánico enorme para Instagram/TikTok. Se incluye como producto gancho del menú inicial.',
    category: 'Hito Logrado',
    authorId: 'partner-1',
    authorName: 'Socio A',
    date: '2026-09-01',
  },
];

export const INITIAL_MILESTONES: Milestone[] = [
  {
    id: 'ms-1',
    title: 'Firma de Acta Constitutiva & Registro IMPI',
    phase: 'Fase I: Legal & Formalización',
    deadline: 'Octubre 2026',
    status: 'in_progress',
    progress: 75,
  },
  {
    id: 'ms-2',
    title: 'Arrendamiento & Obra Civil (Puebla)',
    phase: 'Fase I: Consolidación',
    deadline: 'Noviembre 2026',
    status: 'pending',
    progress: 30,
  },
  {
    id: 'ms-3',
    title: 'Montaje de Equipamiento & Calibración de Hornos',
    phase: 'Fase I: Consolidación',
    deadline: 'Diciembre 2026',
    status: 'pending',
    progress: 10,
  },
  {
    id: 'ms-4',
    title: 'Apertura Oficial Boutique Grab & Go Puebla',
    phase: 'Fase I: Lanzamiento',
    deadline: 'Enero 2027',
    status: 'pending',
    progress: 0,
  },
];
